name: CI

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  test:
    uses: ./.github/workflows/tests.yml
